# Generated by Django 4.2.26 on 2025-11-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_category_color_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Optional hex colour (jaise #ff6f00).', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional icon for category (Instamart style).', null=True, upload_to='category_icons/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Home page pe sort karne ke liye number (chhota number pehle aayega).'),
        ),
    ]
